---
# This playbook will install jsonserver and seed a JSON file for testing Morpheus inputs/option lists

- name: update apt
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add repository
  shell: >
    curl -sL https://deb.nodesource.com/setup_{{ nodejs_version_map[nodejs_version] }} | bash -

 - name: install software
    apt:
      name: nodejs
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
 - name: copy json file
  template: src=app.json.j2 dest=/home/ubuntu/app.json mode=0644
    

 - name: watch file
   shell: 'nohup json-server -H 172.30.0.11 -p 8101 --watch app.json < /dev/null &'
