---
- name: Add a user
  hosts: all
  gather_facts: yes
  tasks:
  - name: Add User
    win_user:
      name: "{{ morpheus['customOptions']['username'] }}"
      password: "{{ lookup('cypher','secret=secret/userpass') | password_hash('sha512') }}"
      state: present
    when: '"Windows" in ansible_distribution'
