---
- name: This is to add user on instances
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Add a user
    user:
      name: kreeves
      password: "{{ lookup('cypher','secret=secret/userpass') }}"
      state: present
